{
 "title": "HTTP Request Trace Dashboard",
 "description": "Shows high level LLM successes and failures.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "2981aa81", "operator": "=", "scope": "span" }
     ],
     "limit": 1000,
     "metricsQueryType": "instant",
     "query": "{}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Failed Validations",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "limit": 1000,
     "metricsQueryType": "range",
     "query": "{name=\"step\" } | select(span.output.value)",
     "spss": 10,
     "tableType": "spans"
    }
   ]
  },
  {
   "title": "Total Failed Validations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": 1000,
     "metricsQueryType": "range",
     "query": "{name=~\"bookinfo-review\" } | select(span.output.value)",
     "tableType": "spans"
    }
   ]
  },
  { "title": "Behavior", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Run duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 11 },
   "targets": [
    {
     "filters": [
      { "id": "0b3c1488", "operator": "=", "scope": "span" }
     ],
     "limit": 1000,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Execution Errors",
   "type": "timeseries",
   "description": "These occur when a runtime error is invoked and the Guard is not able to fulfill a request as exepected",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 11 },
   "targets": [
    {
     "filters": [
      { "id": "9a2ba9ae", "operator": "=", "scope": "span" },
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "error",
       "valueType": "keyword"
      },
      {
       "id": "span-name",
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [ "step" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Trace Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    { "limit": 20, "metricsQueryType": "range", "query": "{}", "tableType": "traces" }
   ]
  }
 ]
}