apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: stack
  namespace: tracing-system
  finalizers:
    - tempo.grafana.com/finalizer
  labels:
    app.kubernetes.io/managed-by: tempo-operator
    tempo.grafana.com/distribution: openshift
spec:
  observability:
    grafana:
      instanceSelector: {}
    metrics: {}
    tracing:
      jaeger_agent_endpoint: 'localhost:6831'
      otlp_http_endpoint: 'http://localhost:4320'
  timeout: 30s
  resources:
    total:
      limits:
        cpu: '2'
        memory: 2Gi
  search:
    defaultResultLimit: 20
    maxDuration: 0s
  tenants:
    authentication:
      - tenantId: 1610b0c3-c509-4592-a256-a1871353dbfa
        tenantName: dev
      - tenantId: 1610b0c3-c509-4592-a256-a1871353dbfb
        tenantName: prod
    mode: openshift
  managementState: Managed
  limits:
    global:
      ingestion: {}
      query:
        maxSearchDuration: 0s
  serviceAccount: tempo-stack
  images: {}
  template:
    compactor:
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      replicas: 1
    distributor:
      component:
        nodeSelector:
          node-role.kubernetes.io/worker: ''
        replicas: 1
      tls:
        enabled: false
    gateway:
      component:
        nodeSelector:
          node-role.kubernetes.io/worker: ''
        replicas: 1
      enabled: true
      ingress:
        route:
          termination: reencrypt
        type: route
      rbac:
        enabled: false
    ingester:
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      replicas: 1
    querier:
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      replicas: 1
    queryFrontend:
      component:
        nodeSelector:
          node-role.kubernetes.io/worker: ''
        replicas: 1
      jaegerQuery:
        enabled: true
        ingress:
          route: {}
        monitorTab:
          enabled: false
          prometheusEndpoint: ''
        servicesQueryDuration: 72h0m0s
        tempoQuery: {}
  replicationFactor: 1
  storage:
    secret:
      name: tempo-s3
      type: s3
    tls:
      enabled: false
  storageSize: 1Gi
  hashRing:
    memberlist: {}
  retention:
    global:
      traces: 24h0m0s
